-- Insert comprehensive interests organized by category
INSERT INTO public.interests (name, category) VALUES
-- Sports & Fitness
('Gym', 'Sports & Fitness'),
('Running', 'Sports & Fitness'),
('Yoga', 'Sports & Fitness'),
('Swimming', 'Sports & Fitness'),
('Cycling', 'Sports & Fitness'),
('Tennis', 'Sports & Fitness'),
('Football', 'Sports & Fitness'),
('Basketball', 'Sports & Fitness'),
('Cricket', 'Sports & Fitness'),
('Badminton', 'Sports & Fitness'),
('Hiking', 'Sports & Fitness'),
('Martial Arts', 'Sports & Fitness'),
('Dance', 'Sports & Fitness'),
('Rock Climbing', 'Sports & Fitness'),
('Volleyball', 'Sports & Fitness'),

-- Music
('Singing', 'Music'),
('Guitar', 'Music'),
('Piano', 'Music'),
('Drums', 'Music'),
('DJing', 'Music'),
('Classical Music', 'Music'),
('Hip Hop', 'Music'),
('Pop Music', 'Music'),
('Rock Music', 'Music'),
('EDM', 'Music'),
('Bollywood Music', 'Music'),
('Jazz', 'Music'),
('K-Pop', 'Music'),

-- Entertainment
('Movies', 'Entertainment'),
('Netflix', 'Entertainment'),
('Anime', 'Entertainment'),
('Gaming', 'Entertainment'),
('Stand-up Comedy', 'Entertainment'),
('Theatre', 'Entertainment'),
('Podcasts', 'Entertainment'),
('Board Games', 'Entertainment'),
('Video Games', 'Entertainment'),
('K-Drama', 'Entertainment'),
('Reality TV', 'Entertainment'),

-- Creative Arts
('Photography', 'Creative Arts'),
('Painting', 'Creative Arts'),
('Drawing', 'Creative Arts'),
('Writing', 'Creative Arts'),
('Poetry', 'Creative Arts'),
('Blogging', 'Creative Arts'),
('Fashion', 'Creative Arts'),
('Makeup', 'Creative Arts'),
('Crafts', 'Creative Arts'),
('Interior Design', 'Creative Arts'),
('Graphic Design', 'Creative Arts'),
('Video Editing', 'Creative Arts'),

-- Food & Drinks
('Cooking', 'Food & Drinks'),
('Baking', 'Food & Drinks'),
('Coffee', 'Food & Drinks'),
('Tea', 'Food & Drinks'),
('Wine', 'Food & Drinks'),
('Craft Beer', 'Food & Drinks'),
('Fine Dining', 'Food & Drinks'),
('Street Food', 'Food & Drinks'),
('Vegetarian', 'Food & Drinks'),
('Vegan', 'Food & Drinks'),
('Foodie', 'Food & Drinks'),
('BBQ', 'Food & Drinks'),

-- Travel & Outdoors
('Traveling', 'Travel & Outdoors'),
('Road Trips', 'Travel & Outdoors'),
('Camping', 'Travel & Outdoors'),
('Beach', 'Travel & Outdoors'),
('Mountains', 'Travel & Outdoors'),
('Adventure Sports', 'Travel & Outdoors'),
('Backpacking', 'Travel & Outdoors'),
('Scuba Diving', 'Travel & Outdoors'),
('Trekking', 'Travel & Outdoors'),
('Nature', 'Travel & Outdoors'),
('Bird Watching', 'Travel & Outdoors'),
('Stargazing', 'Travel & Outdoors'),

-- Technology
('Coding', 'Technology'),
('AI & ML', 'Technology'),
('Startups', 'Technology'),
('Gadgets', 'Technology'),
('Cryptocurrency', 'Technology'),
('Robotics', 'Technology'),
('Space Tech', 'Technology'),
('Cybersecurity', 'Technology'),

-- Lifestyle
('Meditation', 'Lifestyle'),
('Spirituality', 'Lifestyle'),
('Astrology', 'Lifestyle'),
('Self-improvement', 'Lifestyle'),
('Volunteering', 'Lifestyle'),
('Animal Lover', 'Lifestyle'),
('Dogs', 'Lifestyle'),
('Cats', 'Lifestyle'),
('Gardening', 'Lifestyle'),
('Sustainability', 'Lifestyle'),
('Mental Health', 'Lifestyle'),
('Fitness', 'Lifestyle'),

-- Books & Learning
('Reading', 'Books & Learning'),
('Fiction', 'Books & Learning'),
('Non-fiction', 'Books & Learning'),
('History', 'Books & Learning'),
('Philosophy', 'Books & Learning'),
('Science', 'Books & Learning'),
('Psychology', 'Books & Learning'),
('Languages', 'Books & Learning'),
('Trivia', 'Books & Learning'),
('News', 'Books & Learning'),

-- Social
('Parties', 'Social'),
('Nightlife', 'Nightlife & Social'),
('Clubbing', 'Nightlife & Social'),
('Karaoke', 'Nightlife & Social'),
('Social Events', 'Social'),
('Networking', 'Social'),
('Festivals', 'Social'),
('Concerts', 'Social'),
('Sports Events', 'Social'),
('Brunches', 'Social');